### ISSUE TITLE
math mutator shouldn't mutate +- 0 and other insignificant math mutation

### ISSUE THREAD

**Issue by hydroflame** [hydroflame/godzilla#11]
and yes those exist for readability, like 

    m0[row+0], m0[row+4], m0[row+8], m0[row+12]

**Comment by pcasaretto** [comment]
https://github.com/hydroflame/godzilla/commit/ca9b2b9b6d50a509d11654790cd66ebe642878e7 fixed this?

**Comment by hydroflame** [comment]
Close, assignements should follow these rules too
